// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef INTAKE_H
#define INTAKE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Intake: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities

	std::shared_ptr<DoubleSolenoid> actuator;
	std::shared_ptr<CANTalon> leftSpinner;
	std::shared_ptr<CANTalon> rightSpinner;


public:

	enum ActuatorValue {kAcuatorOpen = DoubleSolenoid::kForward, kActuatorClosed = DoubleSolenoid::kReverse };

	Intake();
	void InitDefaultCommand();

	//...........Actuator..........

	bool IsActuatorClosed();

	void SetActuator(ActuatorValue value);

};

#endif
