// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#include "Lights.h"
#include "../RobotMap.h"
#include "../Commands/LightsOn.h"


Lights::Lights() : Subsystem("Lights") {
    heimdallGlow = RobotMap::lightsHeimdallGlow;
    leftUnderGlow = RobotMap::lightsLeftUnderGlow;
    rightUnderGlow = RobotMap::lightsRightUnderGlow;

    heimdallGlow->Set(Relay::kForward);
    leftUnderGlow->Set(Relay::kForward);
    rightUnderGlow->Set(Relay::kForward);

}

void Lights::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
	SetDefaultCommand(new LightsOn());

}


// Put methods for controlling this subsystem
// here. Call these from Commands.

