// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<DoubleSolenoid> elevatorhaySqueeze;
	static std::shared_ptr<DigitalInput> elevatorrightHaySqueezeSensor;
	static std::shared_ptr<DigitalInput> elevatorleftHaySqueezeSensor;
	static std::shared_ptr<DoubleSolenoid> elevatorbrake;
	static std::shared_ptr<CANTalon> elevatorleftSpool;
	static std::shared_ptr<CANTalon> elevatorrightSpool;
	static std::shared_ptr<DigitalInput> chassisleftLightSensor;
	static std::shared_ptr<DigitalInput> chassisrightLightSensor;
	static std::shared_ptr<CANTalon> chassisleftFrontWheel;
	static std::shared_ptr<CANTalon> chassisleftRearWheel;
	static std::shared_ptr<CANTalon> chassisrightFrontWheel;
	static std::shared_ptr<CANTalon> chassisrightRearWheel;
	static std::shared_ptr<DoubleSolenoid> intakeactuator;
	static std::shared_ptr<CANTalon> intakeleftSpinner;
	static std::shared_ptr<CANTalon> intakerightSpinner;
	static std::shared_ptr<Relay> lightsheimdallGlow;
	static std::shared_ptr<Relay> lightsleftUnderGlow;
	static std::shared_ptr<Relay> lightsrightUnderGlow;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
